title: Adding a public variable and setting it in the Inspector
hero_image: images/banner.png
description: Adding a public variable and setting it in the Inspector.
version: 4
listed: false
copyedit: false
last_tested: "2021-11-29"
steps:
  - title: Adding a public variable and setting it in the Inspector
