title: unity-variable-inspector
hero_image: images/banner.png
description: unity-variable-inspector description
version: 4
listed: false
copyedit: false
last_tested: "2021-11-29"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
