title: Add a public variable and set it in the Inspector
hero_image: images/banner.png
description: Add a public variable and set it in the Inspector
version: 4
listed: false
copyedit: false
last_tested: "2021-11-29"
steps:
  - title: Add a public variable and set it in the Inspector
